language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
before_install:
  - sudo apt-get install libopencv-dev
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov
  - mkdir build
  - cd build
  - cmake .. && make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'